'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Copy,ArrowUpFromLine,RefreshCw,ExternalLink,ShieldCheck,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableRow,TableCell,TableHeader,TableHead} from '@/components/ui/table';
type Transfer={id:string,kind:string,amount:number,fee:number,destination:string,signature:string,status:string,error:string|null,created:number};
type WalletData={configured:boolean,address?:string|null,balance:number,transfers:Transfer[],review?:Transfer[]};
const sol=(v:number)=>(v/1e9).toLocaleString('en',{maximumFractionDigits:9});
async function request(path:string,body?:unknown){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const data=await response.json() as WalletData&{error?:string};if(!response.ok)throw new Error(data.error??'The wallet request failed.');return data;}
export default function FundedWallet({treasury=false}:{treasury?:boolean}){
 const path=treasury?'/api/treasury':'/api/wallet';
 const [data,setData]=useState<WalletData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[stage,setStage]=useState('edit'),[amount,setAmount]=useState(''),[destination,setDestination]=useState(''),[copied,setCopied]=useState(false);
 const operation=useRef<string|null>(null),depositOperation=useRef<string|null>(null);
 const load=useCallback(async()=>{try{setData(await request(path))}catch(e){setError((e as Error).message)}},[path]);
 useEffect(()=>{void load()},[load]);
 const action=async(body:unknown)=>{setBusy(true);setError('');try{await request(path,body);await load();return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}};
 const deposit=async()=>{depositOperation.current??=crypto.randomUUID();if(await action({action:'deposit',id:depositOperation.current}))depositOperation.current=null;};
 const withdraw=async()=>{operation.current??=crypto.randomUUID();if(await action({action:'withdraw',id:operation.current,amount,destination})){setOpen(false);setStage('edit');operation.current=null;setAmount('');setDestination('');}};
 return <section className="panel funded-wallet" style={{margin:'26px 0 32px'}}><div className="panel-title"><h2>{treasury?'Solana house treasury':'Your Solana wallet'}</h2><span className="demo-tag">DEVNET · TEST SOL</span></div>
 <p className="muted">{treasury?'Only earned house fees are available here. Player balances and reserved match pots cannot be withdrawn by this control.':'Fund a match using Solana’s test network. Devnet SOL has no monetary value and is separate from demo credits.'}</p>
 {error&&<p className="error" role="alert" style={{marginTop:15}}>{error}</p>}
 {!data?<p className="muted" style={{marginTop:20}}>{error?'Sign in and create a player profile to use the wallet.':'Loading your wallet…'}</p>:!data.configured?<div className="callout"><ShieldCheck/><div><h3>Solana funding is not connected yet.</h3><p>The wallet controls will be available after the development payment service is configured. Real SOL is not accepted.</p></div></div>:<>
 <div className="wallet-value">{sol(data.balance)} <small>devnet SOL available</small></div>
 {data.address&&<><label className="field">Your deposit address · devnet only<input readOnly className="input" value={data.address} onFocus={e=>e.target.select()}/></label><div className="row-actions"><button className="btn" onClick={async()=>{try{await navigator.clipboard.writeText(data.address!);setCopied(true)}catch{setError('Select and copy the address above.')}}}>{copied?<Check/>:<Copy/>}{copied?'Copied':'Copy address'}</button><a className="btn" href={`https://explorer.solana.com/address/${data.address}?cluster=devnet`} target="_blank" rel="noreferrer">View wallet <ExternalLink/></a></div><p className="fine" style={{marginTop:12}}>Send test SOL to this address, then check the deposit. Funds become available after a confirmed transfer into the player pool. The network fee is deducted from the deposit.</p></>}
 <div className="wallet-actions">{!treasury&&<button className="btn btn-primary" disabled={busy} onClick={()=>void deposit()}><RefreshCw/>Check deposit</button>}<button className="btn" disabled={busy||data.balance<=0} onClick={()=>{setOpen(true);setStage('edit')}}><ArrowUpFromLine/>{treasury?'Transfer earned fees':'Withdraw test SOL'}</button><button className="btn" onClick={()=>void load()} disabled={busy}>Refresh balance</button></div>
 <p className="fine">Withdrawal amounts plus network fees are reserved immediately. An uncertain transfer remains reserved until its status is resolved.</p>
 {data.transfers.length>0&&<div className="table-card" style={{marginTop:25}}><Table><TableHeader><TableRow><TableHead>Transfer</TableHead><TableHead>Amount</TableHead><TableHead>Network fee</TableHead><TableHead>Status</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{data.transfers.map(t=><TableRow key={t.id}><TableCell>{t.kind}</TableCell><TableCell>{sol(t.amount)}</TableCell><TableCell>{sol(t.fee)}</TableCell><TableCell><b className={t.status==='finalized'?'lime':''}>{t.status}</b>{t.error&&<p className="fine" style={{maxWidth:250,whiteSpace:'normal'}}>{t.error}</p>}</TableCell><TableCell><div className="row-actions"><a className="btn" href={`https://explorer.solana.com/tx/${t.signature}?cluster=devnet`} target="_blank" rel="noreferrer" aria-label="View transaction"><ExternalLink/></a>{['pending','review'].includes(t.status)&&<button className="btn" disabled={busy} onClick={()=>void action({action:'reconcile',id:t.id})}>Recheck</button>}</div></TableCell></TableRow>)}</TableBody></Table></div>}
 {treasury&&!!data.review?.length&&<div style={{marginTop:20}}><h3>Transfers needing review</h3><p className="fine">These funds remain reserved. Recheck after verifying the transaction status; no replacement payment is created.</p>{data.review.map(t=><div key={t.id} className="math-line" style={{gap:12,marginTop:12}}><span>{t.kind} · {t.signature.slice(0,12)}…</span><button className="btn" disabled={busy} onClick={()=>void action({action:'reconcile',id:t.id})}>Recheck</button></div>)}</div>}
 </>}
 <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="dialog-dark"><DialogTitle>{stage==='confirm'?'Confirm your transfer':'Withdraw devnet SOL'}</DialogTitle><DialogDescription>{stage==='confirm'?'Confirm the full destination address and amount. A blockchain transfer cannot be reversed. The network fee is added to the reserved amount.':'Enter an external Solana wallet on devnet. These funds are for testing only.'}</DialogDescription>
 {stage==='edit'?<form onSubmit={e=>{e.preventDefault();operation.current=null;setStage('confirm')}}><label className="field">Destination address<input className="input" value={destination} onChange={e=>setDestination(e.target.value.trim())} required minLength={32} maxLength={44} autoComplete="off"/></label><label className="field">Amount · devnet SOL<input className="input" value={amount} onChange={e=>setAmount(e.target.value)} required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,9})?" placeholder="0.1"/></label><button className="btn btn-primary full" type="submit">Review transfer</button></form>:<><p style={{overflowWrap:'anywhere'}}>To: <strong>{destination}</strong></p><p>Amount: <strong>{amount} devnet SOL</strong></p><p className="fine">A network fee of up to 0.001 devnet SOL will be added. Available balance must cover both the transfer and the fee.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="row-actions"><button className="btn" disabled={busy} onClick={()=>setStage('edit')}>Back</button><button className="btn btn-primary" disabled={busy} onClick={()=>void withdraw()}>{busy?'Submitting…':'Confirm transfer'}</button></div></>}
 </DialogContent></Dialog></section>
}
