import {settle} from '@/lib/matches';
import {getChatGPTUser} from '../../chatgpt-auth';
import {database,adminId} from '@/db/raw';
import {initial,simulate,Game} from '@/lib/engine';
import {cashAccountId,ensureCashAccount,ensureWallet,settings} from '@/lib/payments/service';
import {launchStatus,requireDevnet} from '@/lib/payments/policy';
export const dynamic='force-dynamic';
const stakes=[50000000,100000000,1000000000,5000000000,10000000000];
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}});
type Run={id:string;match_id:string;user_id:string;state:string;revision:number;score:number;done:number;forfeit:number};
type Match={id:string;seed:number;stake:number;asset:string;p1:string;p2:string|null;settled:number;winner:string|null};
async function snapshot(uid:string,asset='demo'){const db=database();const pending=(await db.prepare('SELECT DISTINCT match_id FROM runs WHERE user_id=? AND done=1').bind(uid).all<{match_id:string}>()).results;for(const m of pending)await settle(m.match_id);const [player,history,transactions,leaders,active]=await Promise.all([db.prepare('SELECT * FROM players WHERE id=?').bind(uid).first(),db.prepare(`SELECT m.*,r.id AS run_id,r.score,r.done,r.forfeit,r.revision,CASE WHEN m.p1=? THEN p2.name ELSE p1.name END AS opponent,CASE WHEN m.settled=1 THEN other.score ELSE NULL END AS opponent_score FROM runs r JOIN matches m ON r.match_id=m.id LEFT JOIN players p1 ON p1.id=m.p1 LEFT JOIN players p2 ON p2.id=m.p2 LEFT JOIN runs other ON other.match_id=m.id AND other.user_id<>r.user_id WHERE r.user_id=? AND m.asset=? ORDER BY m.created DESC LIMIT 50`).bind(uid,uid,asset).all(),db.prepare('SELECT * FROM ledger WHERE user_id=? ORDER BY created DESC LIMIT 50').bind(uid).all(),(asset==='demo'?db.prepare(`SELECT p.name,p.id,COALESCE(SUM(l.amount),0) AS pnl,COUNT(DISTINCT m.id) AS games FROM players p JOIN ledger l ON l.user_id=p.id JOIN matches m ON m.id=l.match_id AND m.settled=1 GROUP BY p.id ORDER BY pnl DESC,p.name ASC LIMIT 50`):db.prepare(`SELECT p.name,p.id,SUM(l.amount) AS pnl,COUNT(DISTINCT m.id) AS games FROM players p JOIN cash_accounts a ON a.user_id=p.id AND a.network='devnet' JOIN cash_ledger l ON l.account_id=a.id JOIN matches m ON m.id=l.reference AND m.settled=1 AND m.asset='devnet' WHERE l.kind IN ('match_entry','match_payout') GROUP BY p.id ORDER BY pnl DESC,p.name ASC LIMIT 50`)).all(),db.prepare('SELECT r.*,m.asset FROM runs r JOIN matches m ON m.id=r.match_id WHERE r.user_id=? AND r.done=0').bind(uid).first<Run>()]);const cash=await db.prepare('SELECT balance FROM cash_accounts WHERE id=?').bind(cashAccountId(uid)).first<{balance:number}>();return {asset,cashBalance:cash?.balance??0,launch:launchStatus(settings()),player,matches:history.results,transactions:transactions.results,leaders:leaders.results,active:active?{...active,state:JSON.parse(active.state)}:null,isAdmin:!!adminId()&&uid===adminId()}}
export async function GET(req:Request){try{const asset=new URL(req.url).searchParams.get('asset')==='devnet'?'devnet':'demo';const user=await getChatGPTUser();if(!user)return json({authenticated:false});const data=await snapshot(user.userId,asset);return json({authenticated:true,...data})}catch(e){console.error(e);return json({error:'Unable to load demo accounts. You can still play practice.'},503)}}
export async function POST(req:Request){try{if(req.headers.get('origin')!==new URL(req.url).origin)return json({error:'Request origin rejected.'},403);const user=await getChatGPTUser();if(!user)return json({error:'Sign in to save your games.'},401);const uid=user.userId,db=database();const raw=await req.text();if(raw.length>4096)return json({error:'Request too large.'},413);let b;try{b=JSON.parse(raw)}catch{return json({error:'Invalid request.'},400)}
if(b.action==='signup'){const name=String(b.name??'').trim();if(!/^[a-zA-Z0-9_]{3,20}$/.test(name))return json({error:'Use 3–20 letters, numbers or underscores.'},400);await db.prepare('INSERT OR IGNORE INTO players(id,name,created) VALUES(?,?,?)').bind(uid,name,Date.now()).run();if(launchStatus(settings()).configured){try{await ensureWallet(uid);await ensureCashAccount(uid);}catch{/* Account survives temporary wallet provisioning failure; wallet page retries. */}}return json(await snapshot(uid))}
const player=await db.prepare('SELECT id,balance FROM players WHERE id=?').bind(uid).first<{id:string,balance:number}>();if(!player)return json({error:'Create your player profile first.'},403);
if(b.action==='start'){const asset=b.asset??'demo';if(asset!=='demo'&&asset!=='devnet')return json({error:'Unsupported match currency.'},400);if(asset==='devnet'){requireDevnet(settings());await ensureCashAccount(uid);}const active=await db.prepare('SELECT r.*,m.asset FROM runs r JOIN matches m ON m.id=r.match_id WHERE r.user_id=? AND r.done=0').bind(uid).first<Run>();if(active)return json({run:{...active,state:JSON.parse(active.state)}});const stake=Number(b.stake);if(!stakes.includes(stake))return json({error:'Choose one of the five entry amounts.'},400);const available=asset==='demo'?player.balance:(await db.prepare('SELECT balance FROM cash_accounts WHERE id=?').bind(cashAccountId(uid)).first<{balance:number}>())?.balance??0;if(available<stake)return json({error:asset==='demo'?'Not enough demo SOL. Practice is always free.':'Not enough deposited devnet SOL. Open your wallet to fund it.'},400);let m=await db.prepare('SELECT * FROM matches WHERE stake=? AND asset=? AND p2 IS NULL AND p1<>? AND settled=0 ORDER BY created ASC LIMIT 1').bind(stake,asset,uid).first<Match>();const id=crypto.randomUUID(),now=Date.now();const ops=[];if(m){ops.push(db.prepare('UPDATE matches SET p2=? WHERE id=? AND p2 IS NULL AND settled=0').bind(uid,m.id))}else{m={id:crypto.randomUUID(),seed:crypto.getRandomValues(new Uint32Array(1))[0],stake,asset,p1:uid,p2:null,settled:0,winner:null};ops.push(db.prepare('INSERT INTO matches(id,seed,stake,asset,p1,created) VALUES(?,?,?,?,?,?)').bind(m.id,m.seed,stake,asset,uid,now))}const state=initial(m.seed);ops.push(db.prepare('INSERT INTO runs(id,match_id,user_id,state,created) SELECT ?,?,?,?,? FROM matches WHERE id=? AND (p1=? OR p2=?)').bind(id,m.id,uid,JSON.stringify(state),now,m.id,uid,uid));if(asset==='devnet'){
 await ensureCashAccount('escrow:'+m.id);
 ops.push(db.prepare("INSERT INTO cash_ledger(id,account_id,kind,amount,reference,created) SELECT ?,?,'match_entry',?,?,? FROM runs WHERE id=?").bind(`${id}:cash:entry`,cashAccountId(uid),-stake,m.id,now,id));
 ops.push(db.prepare("INSERT INTO cash_ledger(id,account_id,kind,amount,reference,created) SELECT ?,?,'escrow_funding',?,?,? FROM runs WHERE id=?").bind(`${id}:cash:escrow`,cashAccountId('escrow:'+m.id),stake,m.id,now,id));
 }else{ops.push(db.prepare("INSERT INTO ledger(id,user_id,match_id,kind,amount,created) SELECT ?,?,?,'entry',?,? FROM runs WHERE id=?").bind(`${id}:entry`,uid,m.id,-stake,now,id));}await db.batch(ops);const run=await db.prepare('SELECT * FROM runs WHERE id=? AND user_id=?').bind(id,uid).first<Run>();if(!run)return json({error:'That opponent was just matched. Please try again.'},409);return json({run:{...run,asset,state:JSON.parse(run.state)}})}
if(b.action==='shot'||b.action==='forfeit'){const run=await db.prepare('SELECT r.*,m.asset FROM runs r JOIN matches m ON m.id=r.match_id WHERE r.id=? AND r.user_id=?').bind(String(b.runId),uid).first<Run>();if(!run)return json({error:'Game not found.'},404);if(run.done||run.revision!==b.revision)return json({error:'This game changed in another tab. Reload to resume.'},409);let state=JSON.parse(run.state) as Game;const forfeit=b.action==='forfeit';if(forfeit)state.over=true;else{if(typeof b.angle!=='number'||!Number.isFinite(b.angle)||b.angle<8||b.angle>172)return json({error:'Invalid aim angle.'},400);state=simulate(state,b.angle)}const result=await db.prepare('UPDATE runs SET state=?,score=?,done=?,forfeit=?,revision=revision+1 WHERE id=? AND user_id=? AND revision=? AND done=0').bind(JSON.stringify(state),state.score,state.over?1:0,forfeit?1:0,run.id,uid,run.revision).run();if(!result.meta.changes)return json({error:'This shot was already processed. Reload to resume.'},409);if(state.over)await settle(run.match_id);return json({run:{...run,state,score:state.score,done:state.over?1:0,forfeit:forfeit?1:0,revision:run.revision+1}})}
if(b.action==='admin'){if(!adminId()||uid!==adminId())return json({error:'Treasury access is restricted to the configured administrator.'},403);return json(await db.prepare("SELECT COUNT(*) AS settled_matches,COALESCE(SUM(fee),0) AS fees FROM matches WHERE settled=1 AND asset='demo'").first())}
return json({error:'Unknown action.'},400)}catch(e){console.error(e);return json({error:'The request could not be completed. Reload to check your saved game before trying again.'},503)}}
